name: Publish Docker
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE: 'workflow-service'
      REPO: 'ukhomeofficedigital/workflow-service'
    steps:
      - uses: actions/checkout@v2
      - uses: joschi/setup-jdk@v1
        with:
          java-version: 'openjdk14'
          architecture: 'x64'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run tests
        run: ./gradlew clean test
      - name: Run build
        run: ./gradlew clean build
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ env.IMAGE }}:latest
      - uses: anchore/scan-action@master
        with:
          image-reference: "${{ env.IMAGE }}:latest"
          dockerfile-path: "./Dockerfile"
          fail-build: false
          include-app-packages: true
      - name: anchore inline scan JSON results
        run: cat ./anchore-reports/vulnerabilities.json;
      - name: Publish to Quay Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: ${{ env.REPO}}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: quay.io
          cache: true
          snapshot: true
          tags: "${{ github.sha }}"
      - uses: 8398a7/action-slack@v2
        with:
          status: ${{ job.status }}
          author_name: Github # default: 8398a7@action-slack
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # optional
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
